GET http://localhost:3000/projects

###
GET http://localhost:3000/projects/b53d3c48-8747-47cc-ab9d-994697cb74bc

###
# @name createProject
POST http://localhost:3000/projects
Content-Type: application/json

{
  "name": "Project 1",
  "description": "First project"
}

###
@project_id = {{ createProject.response.body.id }}

###
PATCH http://localhost:3000/projects/{{project_id}}
Content-Type: application/json

{
  "name": "Updated Project",
  "description": "Updated Project Description",
  "started_at": "2020-01-01"
}

###
POST http://localhost:3000/projects/{{project_id}}/start
Content-Type: application/json

{
  "started_at": "2020-01-01"
}